namespace SDLSharp
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    [Flags]
    public enum BlendMode
    {
        None = 0x00000000,
        Blend = 0x00000001,
        Add = 0x00000002,
        Mod = 0x00000004,
        Mul = 0x00000008,
        Invalid = 0x7FFFFFFF
    }

    public enum TextureFilter
    {
        Linear,
        Nearest,
        Best
    }


    [Flags]
    public enum FontStyle
    {
        Normal = 0x00,
        Bold = 0x01,
        Italic = 0x02,
        Underline = 0x04,
        Strikethrough = 0x08
    }

    public enum FontHinting
    {
        Normal = 0,
        Light = 1,
        Mono = 2,
        None = 3,
        LightSubPixel = 4
    }

    public enum MusicFinishReason
    {
        Finished,
        Interrupted
    }
    public enum HorizontalAlignment
    {
        Left,
        Right,
        Center,
        Stretch
    }

    public enum VerticalAlignment
    {
        Top,
        Bottom,
        Center,
        Stretch
    }

    public enum MouseButton
    {
        None = 0,
        Left = 1,
        Middle = 2,
        Right = 3,
        X1 = 4,
        X2 = 5
    }

    public enum KeyButtonState
    {
        Invalid = -1,
        Released = 0,
        Pressed = 1
    }

    public enum MouseWheelDirection
    {
        Normal = 0,
        Flipped = 1
    }

    public enum LogPriority
    {
        None = 0,
        Verbose = 1,
        Debug = 2,
        Info = 3,
        Warn = 4,
        Error = 5,
        Critical = 6,
        Max = 7
    }

    public enum LogCategory
    {
        APPLICATION,
        ERROR,
        ASSERT,
        SYSTEM,
        AUDIO,
        VIDEO,
        RENDER,
        INPUT,
        TEST,
        RESERVED1,
        RESERVED2,
        RESERVED3,
        RESERVED4,
        RESERVED5,
        RESERVED6,
        RESERVED7,
        RESERVED8,
        RESERVED9,
        RESERVED10,
        CUSTOM,
        MAX
    }


    public enum ScanCode
    {
        SCANCODE_UNKNOWN = 0,
        SCANCODE_A = 4,
        SCANCODE_B = 5,
        SCANCODE_C = 6,
        SCANCODE_D = 7,
        SCANCODE_E = 8,
        SCANCODE_F = 9,
        SCANCODE_G = 10,
        SCANCODE_H = 11,
        SCANCODE_I = 12,
        SCANCODE_J = 13,
        SCANCODE_K = 14,
        SCANCODE_L = 15,
        SCANCODE_M = 16,
        SCANCODE_N = 17,
        SCANCODE_O = 18,
        SCANCODE_P = 19,
        SCANCODE_Q = 20,
        SCANCODE_R = 21,
        SCANCODE_S = 22,
        SCANCODE_T = 23,
        SCANCODE_U = 24,
        SCANCODE_V = 25,
        SCANCODE_W = 26,
        SCANCODE_X = 27,
        SCANCODE_Y = 28,
        SCANCODE_Z = 29,
        SCANCODE_1 = 30,
        SCANCODE_2 = 31,
        SCANCODE_3 = 32,
        SCANCODE_4 = 33,
        SCANCODE_5 = 34,
        SCANCODE_6 = 35,
        SCANCODE_7 = 36,
        SCANCODE_8 = 37,
        SCANCODE_9 = 38,
        SCANCODE_0 = 39,
        SCANCODE_RETURN = 40,
        SCANCODE_ESCAPE = 41,
        SCANCODE_BACKSPACE = 42,
        SCANCODE_TAB = 43,
        SCANCODE_SPACE = 44,
        SCANCODE_MINUS = 45,
        SCANCODE_EQUALS = 46,
        SCANCODE_LEFTBRACKET = 47,
        SCANCODE_RIGHTBRACKET = 48,
        SCANCODE_BACKSLASH = 49,
        SCANCODE_NONUSHASH = 50,
        SCANCODE_SEMICOLON = 51,
        SCANCODE_APOSTROPHE = 52,
        SCANCODE_GRAVE = 53,
        SCANCODE_COMMA = 54,
        SCANCODE_PERIOD = 55,
        SCANCODE_SLASH = 56,
        SCANCODE_CAPSLOCK = 57,
        SCANCODE_F1 = 58,
        SCANCODE_F2 = 59,
        SCANCODE_F3 = 60,
        SCANCODE_F4 = 61,
        SCANCODE_F5 = 62,
        SCANCODE_F6 = 63,
        SCANCODE_F7 = 64,
        SCANCODE_F8 = 65,
        SCANCODE_F9 = 66,
        SCANCODE_F10 = 67,
        SCANCODE_F11 = 68,
        SCANCODE_F12 = 69,
        SCANCODE_PRINTSCREEN = 70,
        SCANCODE_SCROLLLOCK = 71,
        SCANCODE_PAUSE = 72,
        SCANCODE_INSERT = 73,
        SCANCODE_HOME = 74,
        SCANCODE_PAGEUP = 75,
        SCANCODE_DELETE = 76,
        SCANCODE_END = 77,
        SCANCODE_PAGEDOWN = 78,
        SCANCODE_RIGHT = 79,
        SCANCODE_LEFT = 80,
        SCANCODE_DOWN = 81,
        SCANCODE_UP = 82,
        SCANCODE_NUMLOCKCLEAR = 83,
        SCANCODE_KP_DIVIDE = 84,
        SCANCODE_KP_MULTIPLY = 85,
        SCANCODE_KP_MINUS = 86,
        SCANCODE_KP_PLUS = 87,
        SCANCODE_KP_ENTER = 88,
        SCANCODE_KP_1 = 89,
        SCANCODE_KP_2 = 90,
        SCANCODE_KP_3 = 91,
        SCANCODE_KP_4 = 92,
        SCANCODE_KP_5 = 93,
        SCANCODE_KP_6 = 94,
        SCANCODE_KP_7 = 95,
        SCANCODE_KP_8 = 96,
        SCANCODE_KP_9 = 97,
        SCANCODE_KP_0 = 98,
        SCANCODE_KP_PERIOD = 99,
        SCANCODE_NONUSBACKSLASH = 100,
        SCANCODE_APPLICATION = 101,
        SCANCODE_POWER = 102,
        SCANCODE_KP_EQUALS = 103,
        SCANCODE_F13 = 104,
        SCANCODE_F14 = 105,
        SCANCODE_F15 = 106,
        SCANCODE_F16 = 107,
        SCANCODE_F17 = 108,
        SCANCODE_F18 = 109,
        SCANCODE_F19 = 110,
        SCANCODE_F20 = 111,
        SCANCODE_F21 = 112,
        SCANCODE_F22 = 113,
        SCANCODE_F23 = 114,
        SCANCODE_F24 = 115,
        SCANCODE_EXECUTE = 116,
        SCANCODE_HELP = 117,
        SCANCODE_MENU = 118,
        SCANCODE_SELECT = 119,
        SCANCODE_STOP = 120,
        SCANCODE_AGAIN = 121,
        SCANCODE_UNDO = 122,
        SCANCODE_CUT = 123,
        SCANCODE_COPY = 124,
        SCANCODE_PASTE = 125,
        SCANCODE_FIND = 126,
        SCANCODE_MUTE = 127,
        SCANCODE_VOLUMEUP = 128,
        SCANCODE_VOLUMEDOWN = 129,
        SCANCODE_LOCKINGCAPSLOCK = 130,
        SCANCODE_LOCKINGNUMLOCK = 131,
        SCANCODE_LOCKINGSCROLLLOCK = 132,
        SCANCODE_KP_COMMA = 133,
        SCANCODE_KP_EQUALSAS400 = 134,
        SCANCODE_INTERNATIONAL1 = 135,
        SCANCODE_INTERNATIONAL2 = 136,
        SCANCODE_INTERNATIONAL3 = 137,
        SCANCODE_INTERNATIONAL4 = 138,
        SCANCODE_INTERNATIONAL5 = 139,
        SCANCODE_INTERNATIONAL6 = 140,
        SCANCODE_INTERNATIONAL7 = 141,
        SCANCODE_INTERNATIONAL8 = 142,
        SCANCODE_INTERNATIONAL9 = 143,
        SCANCODE_LANG1 = 144,
        SCANCODE_LANG2 = 145,
        SCANCODE_LANG3 = 146,
        SCANCODE_LANG4 = 147,
        SCANCODE_LANG5 = 148,
        SCANCODE_LANG6 = 149,
        SCANCODE_LANG7 = 150,
        SCANCODE_LANG8 = 151,
        SCANCODE_LANG9 = 152,
        SCANCODE_ALTERASE = 153,
        SCANCODE_SYSREQ = 154,
        SCANCODE_CANCEL = 155,
        SCANCODE_CLEAR = 156,
        SCANCODE_PRIOR = 157,
        SCANCODE_RETURN2 = 158,
        SCANCODE_SEPARATOR = 159,
        SCANCODE_OUT = 160,
        SCANCODE_OPER = 161,
        SCANCODE_CLEARAGAIN = 162,
        SCANCODE_CRSEL = 163,
        SCANCODE_EXSEL = 164,
        SCANCODE_KP_00 = 176,
        SCANCODE_KP_000 = 177,
        SCANCODE_THOUSANDSSEPARATOR = 178,
        SCANCODE_DECIMALSEPARATOR = 179,
        SCANCODE_CURRENCYUNIT = 180,
        SCANCODE_CURRENCYSUBUNIT = 181,
        SCANCODE_KP_LEFTPAREN = 182,
        SCANCODE_KP_RIGHTPAREN = 183,
        SCANCODE_KP_LEFTBRACE = 184,
        SCANCODE_KP_RIGHTBRACE = 185,
        SCANCODE_KP_TAB = 186,
        SCANCODE_KP_BACKSPACE = 187,
        SCANCODE_KP_A = 188,
        SCANCODE_KP_B = 189,
        SCANCODE_KP_C = 190,
        SCANCODE_KP_D = 191,
        SCANCODE_KP_E = 192,
        SCANCODE_KP_F = 193,
        SCANCODE_KP_XOR = 194,
        SCANCODE_KP_POWER = 195,
        SCANCODE_KP_PERCENT = 196,
        SCANCODE_KP_LESS = 197,
        SCANCODE_KP_GREATER = 198,
        SCANCODE_KP_AMPERSAND = 199,
        SCANCODE_KP_DBLAMPERSAND = 200,
        SCANCODE_KP_VERTICALBAR = 201,
        SCANCODE_KP_DBLVERTICALBAR = 202,
        SCANCODE_KP_COLON = 203,
        SCANCODE_KP_HASH = 204,
        SCANCODE_KP_SPACE = 205,
        SCANCODE_KP_AT = 206,
        SCANCODE_KP_EXCLAM = 207,
        SCANCODE_KP_MEMSTORE = 208,
        SCANCODE_KP_MEMRECALL = 209,
        SCANCODE_KP_MEMCLEAR = 210,
        SCANCODE_KP_MEMADD = 211,
        SCANCODE_KP_MEMSUBTRACT = 212,
        SCANCODE_KP_MEMMULTIPLY = 213,
        SCANCODE_KP_MEMDIVIDE = 214,
        SCANCODE_KP_PLUSMINUS = 215,
        SCANCODE_KP_CLEAR = 216,
        SCANCODE_KP_CLEARENTRY = 217,
        SCANCODE_KP_BINARY = 218,
        SCANCODE_KP_OCTAL = 219,
        SCANCODE_KP_DECIMAL = 220,
        SCANCODE_KP_HEXADECIMAL = 221,
        SCANCODE_LCTRL = 224,
        SCANCODE_LSHIFT = 225,
        SCANCODE_LALT = 226,
        SCANCODE_LGUI = 227,
        SCANCODE_RCTRL = 228,
        SCANCODE_RSHIFT = 229,
        SCANCODE_RALT = 230,
        SCANCODE_RGUI = 231,
        SCANCODE_MODE = 257,
        SCANCODE_AUDIONEXT = 258,
        SCANCODE_AUDIOPREV = 259,
        SCANCODE_AUDIOSTOP = 260,
        SCANCODE_AUDIOPLAY = 261,
        SCANCODE_AUDIOMUTE = 262,
        SCANCODE_MEDIASELECT = 263,
        SCANCODE_WWW = 264,
        SCANCODE_MAIL = 265,
        SCANCODE_CALCULATOR = 266,
        SCANCODE_COMPUTER = 267,
        SCANCODE_AC_SEARCH = 268,
        SCANCODE_AC_HOME = 269,
        SCANCODE_AC_BACK = 270,
        SCANCODE_AC_FORWARD = 271,
        SCANCODE_AC_STOP = 272,
        SCANCODE_AC_REFRESH = 273,
        SCANCODE_AC_BOOKMARKS = 274,
        SCANCODE_BRIGHTNESSDOWN = 275,
        SCANCODE_BRIGHTNESSUP = 276,
        SCANCODE_DISPLAYSWITCH = 277,
        SCANCODE_KBDILLUMTOGGLE = 278,
        SCANCODE_KBDILLUMDOWN = 279,
        SCANCODE_KBDILLUMUP = 280,
        SCANCODE_EJECT = 281,
        SCANCODE_SLEEP = 282,
        SCANCODE_APP1 = 283,
        SCANCODE_APP2 = 284,
        SCANCODE_AUDIOREWIND = 285,
        SCANCODE_AUDIOFASTFORWARD = 286,
        NUM_SCANCODES = 512
    }

    public enum KeyCode
    {
        SCANCODE_MASK = (1 << 30),
        UNKNOWN = 0,

        RETURN = '\r',
        ESCAPE = 27,
        BACKSPACE = '\b',
        TAB = '\t',
        SPACE = ' ',
        EXCLAIM = '!',
        QUOTEDBL = '"',
        HASH = '#',
        PERCENT = '%',
        DOLLAR = '$',
        AMPERSAND = '&',
        QUOTE = '\'',
        LEFTPAREN = '(',
        RIGHTPAREN = ')',
        ASTERISK = '*',
        PLUS = '+',
        COMMA = ',',
        MINUS = '-',
        PERIOD = '.',
        SLASH = '/',
        NUM0 = '0',
        NUM1 = '1',
        NUM2 = '2',
        NUM3 = '3',
        NUM4 = '4',
        NUM5 = '5',
        NUM6 = '6',
        NUM7 = '7',
        NUM8 = '8',
        NUM9 = '9',
        COLON = ':',
        SEMICOLON = ';',
        LESS = '<',
        EQUALS = '=',
        GREATER = '>',
        QUESTION = '?',
        AT = '@',
        LEFTBRACKET = '[',
        BACKSLASH = '\\',
        RIGHTBRACKET = ']',
        CARET = '^',
        UNDERSCORE = '_',
        BACKQUOTE = '`',
        a = 'a',
        b = 'b',
        c = 'c',
        d = 'd',
        e = 'e',
        f = 'f',
        g = 'g',
        h = 'h',
        i = 'i',
        j = 'j',
        k = 'k',
        l = 'l',
        m = 'm',
        n = 'n',
        o = 'o',
        p = 'p',
        q = 'q',
        r = 'r',
        s = 's',
        t = 't',
        u = 'u',
        v = 'v',
        w = 'w',
        x = 'x',
        y = 'y',
        z = 'z',

        CAPSLOCK = (int)ScanCode.SCANCODE_CAPSLOCK | SCANCODE_MASK,

        F1 = (int)ScanCode.SCANCODE_F1 | SCANCODE_MASK,
        F2 = (int)ScanCode.SCANCODE_F2 | SCANCODE_MASK,
        F3 = (int)ScanCode.SCANCODE_F3 | SCANCODE_MASK,
        F4 = (int)ScanCode.SCANCODE_F4 | SCANCODE_MASK,
        F5 = (int)ScanCode.SCANCODE_F5 | SCANCODE_MASK,
        F6 = (int)ScanCode.SCANCODE_F6 | SCANCODE_MASK,
        F7 = (int)ScanCode.SCANCODE_F7 | SCANCODE_MASK,
        F8 = (int)ScanCode.SCANCODE_F8 | SCANCODE_MASK,
        F9 = (int)ScanCode.SCANCODE_F9 | SCANCODE_MASK,
        F10 = (int)ScanCode.SCANCODE_F10 | SCANCODE_MASK,
        F11 = (int)ScanCode.SCANCODE_F11 | SCANCODE_MASK,
        F12 = (int)ScanCode.SCANCODE_F12 | SCANCODE_MASK,

        PRINTSCREEN = (int)ScanCode.SCANCODE_PRINTSCREEN | SCANCODE_MASK,
        SCROLLLOCK = (int)ScanCode.SCANCODE_SCROLLLOCK | SCANCODE_MASK,
        PAUSE = (int)ScanCode.SCANCODE_PAUSE | SCANCODE_MASK,
        INSERT = (int)ScanCode.SCANCODE_INSERT | SCANCODE_MASK,
        HOME = (int)ScanCode.SCANCODE_HOME | SCANCODE_MASK,
        PAGEUP = (int)ScanCode.SCANCODE_PAGEUP | SCANCODE_MASK,
        DELETE = 127,
        END = (int)ScanCode.SCANCODE_END | SCANCODE_MASK,
        PAGEDOWN = (int)ScanCode.SCANCODE_PAGEDOWN | SCANCODE_MASK,
        RIGHT = (int)ScanCode.SCANCODE_RIGHT | SCANCODE_MASK,
        LEFT = (int)ScanCode.SCANCODE_LEFT | SCANCODE_MASK,
        DOWN = (int)ScanCode.SCANCODE_DOWN | SCANCODE_MASK,
        UP = (int)ScanCode.SCANCODE_UP | SCANCODE_MASK,

        NUMLOCKCLEAR = (int)ScanCode.SCANCODE_NUMLOCKCLEAR | SCANCODE_MASK,
        KP_DIVIDE = (int)ScanCode.SCANCODE_KP_DIVIDE | SCANCODE_MASK,
        KP_MULTIPLY = (int)ScanCode.SCANCODE_KP_MULTIPLY | SCANCODE_MASK,
        KP_MINUS = (int)ScanCode.SCANCODE_KP_MINUS | SCANCODE_MASK,
        KP_PLUS = (int)ScanCode.SCANCODE_KP_PLUS | SCANCODE_MASK,
        KP_ENTER = (int)ScanCode.SCANCODE_KP_ENTER | SCANCODE_MASK,
        KP_1 = (int)ScanCode.SCANCODE_KP_1 | SCANCODE_MASK,
        KP_2 = (int)ScanCode.SCANCODE_KP_2 | SCANCODE_MASK,
        KP_3 = (int)ScanCode.SCANCODE_KP_3 | SCANCODE_MASK,
        KP_4 = (int)ScanCode.SCANCODE_KP_4 | SCANCODE_MASK,
        KP_5 = (int)ScanCode.SCANCODE_KP_5 | SCANCODE_MASK,
        KP_6 = (int)ScanCode.SCANCODE_KP_6 | SCANCODE_MASK,
        KP_7 = (int)ScanCode.SCANCODE_KP_7 | SCANCODE_MASK,
        KP_8 = (int)ScanCode.SCANCODE_KP_8 | SCANCODE_MASK,
        KP_9 = (int)ScanCode.SCANCODE_KP_9 | SCANCODE_MASK,
        KP_0 = (int)ScanCode.SCANCODE_KP_0 | SCANCODE_MASK,
        KP_PERIOD = (int)ScanCode.SCANCODE_KP_PERIOD | SCANCODE_MASK,

        APPLICATION = (int)ScanCode.SCANCODE_APPLICATION | SCANCODE_MASK,
        POWER = (int)ScanCode.SCANCODE_POWER | SCANCODE_MASK,
        KP_EQUALS = (int)ScanCode.SCANCODE_KP_EQUALS | SCANCODE_MASK,
        F13 = (int)ScanCode.SCANCODE_F13 | SCANCODE_MASK,
        F14 = (int)ScanCode.SCANCODE_F14 | SCANCODE_MASK,
        F15 = (int)ScanCode.SCANCODE_F15 | SCANCODE_MASK,
        F16 = (int)ScanCode.SCANCODE_F16 | SCANCODE_MASK,
        F17 = (int)ScanCode.SCANCODE_F17 | SCANCODE_MASK,
        F18 = (int)ScanCode.SCANCODE_F18 | SCANCODE_MASK,
        F19 = (int)ScanCode.SCANCODE_F19 | SCANCODE_MASK,
        F20 = (int)ScanCode.SCANCODE_F20 | SCANCODE_MASK,
        F21 = (int)ScanCode.SCANCODE_F21 | SCANCODE_MASK,
        F22 = (int)ScanCode.SCANCODE_F22 | SCANCODE_MASK,
        F23 = (int)ScanCode.SCANCODE_F23 | SCANCODE_MASK,
        F24 = (int)ScanCode.SCANCODE_F24 | SCANCODE_MASK,
        EXECUTE = (int)ScanCode.SCANCODE_EXECUTE | SCANCODE_MASK,
        HELP = (int)ScanCode.SCANCODE_HELP | SCANCODE_MASK,
        MENU = (int)ScanCode.SCANCODE_MENU | SCANCODE_MASK,
        SELECT = (int)ScanCode.SCANCODE_SELECT | SCANCODE_MASK,
        STOP = (int)ScanCode.SCANCODE_STOP | SCANCODE_MASK,
        AGAIN = (int)ScanCode.SCANCODE_AGAIN | SCANCODE_MASK,
        UNDO = (int)ScanCode.SCANCODE_UNDO | SCANCODE_MASK,
        CUT = (int)ScanCode.SCANCODE_CUT | SCANCODE_MASK,
        COPY = (int)ScanCode.SCANCODE_COPY | SCANCODE_MASK,
        PASTE = (int)ScanCode.SCANCODE_PASTE | SCANCODE_MASK,
        FIND = (int)ScanCode.SCANCODE_FIND | SCANCODE_MASK,
        MUTE = (int)ScanCode.SCANCODE_MUTE | SCANCODE_MASK,
        VOLUMEUP = (int)ScanCode.SCANCODE_VOLUMEUP | SCANCODE_MASK,
        VOLUMEDOWN = (int)ScanCode.SCANCODE_VOLUMEDOWN | SCANCODE_MASK,
        KP_COMMA = (int)ScanCode.SCANCODE_KP_COMMA | SCANCODE_MASK,
        KP_EQUALSAS400 = (int)ScanCode.SCANCODE_KP_EQUALSAS400 | SCANCODE_MASK,
        ALTERASE = (int)ScanCode.SCANCODE_ALTERASE | SCANCODE_MASK,
        SYSREQ = (int)ScanCode.SCANCODE_SYSREQ | SCANCODE_MASK,
        CANCEL = (int)ScanCode.SCANCODE_CANCEL | SCANCODE_MASK,
        CLEAR = (int)ScanCode.SCANCODE_CLEAR | SCANCODE_MASK,
        PRIOR = (int)ScanCode.SCANCODE_PRIOR | SCANCODE_MASK,
        RETURN2 = (int)ScanCode.SCANCODE_RETURN2 | SCANCODE_MASK,
        SEPARATOR = (int)ScanCode.SCANCODE_SEPARATOR | SCANCODE_MASK,
        OUT = (int)ScanCode.SCANCODE_OUT | SCANCODE_MASK,
        OPER = (int)ScanCode.SCANCODE_OPER | SCANCODE_MASK,
        CLEARAGAIN = (int)ScanCode.SCANCODE_CLEARAGAIN | SCANCODE_MASK,
        CRSEL = (int)ScanCode.SCANCODE_CRSEL | SCANCODE_MASK,
        EXSEL = (int)ScanCode.SCANCODE_EXSEL | SCANCODE_MASK,
        KP_00 = (int)ScanCode.SCANCODE_KP_00 | SCANCODE_MASK,
        KP_000 = (int)ScanCode.SCANCODE_KP_000 | SCANCODE_MASK,
        THOUSANDSSEPARATOR = (int)ScanCode.SCANCODE_THOUSANDSSEPARATOR | SCANCODE_MASK,
        DECIMALSEPARATOR = (int)ScanCode.SCANCODE_DECIMALSEPARATOR | SCANCODE_MASK,
        CURRENCYUNIT = (int)ScanCode.SCANCODE_CURRENCYUNIT | SCANCODE_MASK,
        CURRENCYSUBUNIT = (int)ScanCode.SCANCODE_CURRENCYSUBUNIT | SCANCODE_MASK,
        KP_LEFTPAREN = (int)ScanCode.SCANCODE_KP_LEFTPAREN | SCANCODE_MASK,
        KP_RIGHTPAREN = (int)ScanCode.SCANCODE_KP_RIGHTPAREN | SCANCODE_MASK,
        KP_LEFTBRACE = (int)ScanCode.SCANCODE_KP_LEFTBRACE | SCANCODE_MASK,
        KP_RIGHTBRACE = (int)ScanCode.SCANCODE_KP_RIGHTBRACE | SCANCODE_MASK,
        KP_TAB = (int)ScanCode.SCANCODE_KP_TAB | SCANCODE_MASK,
        KP_BACKSPACE = (int)ScanCode.SCANCODE_KP_BACKSPACE | SCANCODE_MASK,
        KP_A = (int)ScanCode.SCANCODE_KP_A | SCANCODE_MASK,
        KP_B = (int)ScanCode.SCANCODE_KP_B | SCANCODE_MASK,
        KP_C = (int)ScanCode.SCANCODE_KP_C | SCANCODE_MASK,
        KP_D = (int)ScanCode.SCANCODE_KP_D | SCANCODE_MASK,
        KP_E = (int)ScanCode.SCANCODE_KP_E | SCANCODE_MASK,
        KP_F = (int)ScanCode.SCANCODE_KP_F | SCANCODE_MASK,
        KP_XOR = (int)ScanCode.SCANCODE_KP_XOR | SCANCODE_MASK,
        KP_POWER = (int)ScanCode.SCANCODE_KP_POWER | SCANCODE_MASK,
        KP_PERCENT = (int)ScanCode.SCANCODE_KP_PERCENT | SCANCODE_MASK,
        KP_LESS = (int)ScanCode.SCANCODE_KP_LESS | SCANCODE_MASK,
        KP_GREATER = (int)ScanCode.SCANCODE_KP_GREATER | SCANCODE_MASK,
        KP_AMPERSAND = (int)ScanCode.SCANCODE_KP_AMPERSAND | SCANCODE_MASK,
        KP_DBLAMPERSAND = (int)ScanCode.SCANCODE_KP_DBLAMPERSAND | SCANCODE_MASK,
        KP_VERTICALBAR = (int)ScanCode.SCANCODE_KP_VERTICALBAR | SCANCODE_MASK,
        KP_DBLVERTICALBAR = (int)ScanCode.SCANCODE_KP_DBLVERTICALBAR | SCANCODE_MASK,
        KP_COLON = (int)ScanCode.SCANCODE_KP_COLON | SCANCODE_MASK,
        KP_HASH = (int)ScanCode.SCANCODE_KP_HASH | SCANCODE_MASK,
        KP_SPACE = (int)ScanCode.SCANCODE_KP_SPACE | SCANCODE_MASK,
        KP_AT = (int)ScanCode.SCANCODE_KP_AT | SCANCODE_MASK,
        KP_EXCLAM = (int)ScanCode.SCANCODE_KP_EXCLAM | SCANCODE_MASK,
        KP_MEMSTORE = (int)ScanCode.SCANCODE_KP_MEMSTORE | SCANCODE_MASK,
        KP_MEMRECALL = (int)ScanCode.SCANCODE_KP_MEMRECALL | SCANCODE_MASK,
        KP_MEMCLEAR = (int)ScanCode.SCANCODE_KP_MEMCLEAR | SCANCODE_MASK,
        KP_MEMADD = (int)ScanCode.SCANCODE_KP_MEMADD | SCANCODE_MASK,
        KP_MEMSUBTRACT = (int)ScanCode.SCANCODE_KP_MEMSUBTRACT | SCANCODE_MASK,
        KP_MEMMULTIPLY = (int)ScanCode.SCANCODE_KP_MEMMULTIPLY | SCANCODE_MASK,
        KP_MEMDIVIDE = (int)ScanCode.SCANCODE_KP_MEMDIVIDE | SCANCODE_MASK,
        KP_PLUSMINUS = (int)ScanCode.SCANCODE_KP_PLUSMINUS | SCANCODE_MASK,
        KP_CLEAR = (int)ScanCode.SCANCODE_KP_CLEAR | SCANCODE_MASK,
        KP_CLEARENTRY = (int)ScanCode.SCANCODE_KP_CLEARENTRY | SCANCODE_MASK,
        KP_BINARY = (int)ScanCode.SCANCODE_KP_BINARY | SCANCODE_MASK,
        KP_OCTAL = (int)ScanCode.SCANCODE_KP_OCTAL | SCANCODE_MASK,
        KP_DECIMAL = (int)ScanCode.SCANCODE_KP_DECIMAL | SCANCODE_MASK,
        KP_HEXADECIMAL = (int)ScanCode.SCANCODE_KP_HEXADECIMAL | SCANCODE_MASK,
        LCTRL = (int)ScanCode.SCANCODE_LCTRL | SCANCODE_MASK,
        LSHIFT = (int)ScanCode.SCANCODE_LSHIFT | SCANCODE_MASK,
        LALT = (int)ScanCode.SCANCODE_LALT | SCANCODE_MASK,
        LGUI = (int)ScanCode.SCANCODE_LGUI | SCANCODE_MASK,
        RCTRL = (int)ScanCode.SCANCODE_RCTRL | SCANCODE_MASK,
        RSHIFT = (int)ScanCode.SCANCODE_RSHIFT | SCANCODE_MASK,
        RALT = (int)ScanCode.SCANCODE_RALT | SCANCODE_MASK,
        RGUI = (int)ScanCode.SCANCODE_RGUI | SCANCODE_MASK,
        MODE = (int)ScanCode.SCANCODE_MODE | SCANCODE_MASK,
        AUDIONEXT = (int)ScanCode.SCANCODE_AUDIONEXT | SCANCODE_MASK,
        AUDIOPREV = (int)ScanCode.SCANCODE_AUDIOPREV | SCANCODE_MASK,
        AUDIOSTOP = (int)ScanCode.SCANCODE_AUDIOSTOP | SCANCODE_MASK,
        AUDIOPLAY = (int)ScanCode.SCANCODE_AUDIOPLAY | SCANCODE_MASK,
        AUDIOMUTE = (int)ScanCode.SCANCODE_AUDIOMUTE | SCANCODE_MASK,
        MEDIASELECT = (int)ScanCode.SCANCODE_MEDIASELECT | SCANCODE_MASK,
        WWW = (int)ScanCode.SCANCODE_WWW | SCANCODE_MASK,
        MAIL = (int)ScanCode.SCANCODE_MAIL | SCANCODE_MASK,
        CALCULATOR = (int)ScanCode.SCANCODE_CALCULATOR | SCANCODE_MASK,
        COMPUTER = (int)ScanCode.SCANCODE_COMPUTER | SCANCODE_MASK,
        AC_SEARCH = (int)ScanCode.SCANCODE_AC_SEARCH | SCANCODE_MASK,
        AC_HOME = (int)ScanCode.SCANCODE_AC_HOME | SCANCODE_MASK,
        AC_BACK = (int)ScanCode.SCANCODE_AC_BACK | SCANCODE_MASK,
        AC_FORWARD = (int)ScanCode.SCANCODE_AC_FORWARD | SCANCODE_MASK,
        AC_STOP = (int)ScanCode.SCANCODE_AC_STOP | SCANCODE_MASK,
        AC_REFRESH = (int)ScanCode.SCANCODE_AC_REFRESH | SCANCODE_MASK,
        AC_BOOKMARKS = (int)ScanCode.SCANCODE_AC_BOOKMARKS | SCANCODE_MASK,
        BRIGHTNESSDOWN = (int)ScanCode.SCANCODE_BRIGHTNESSDOWN | SCANCODE_MASK,
        BRIGHTNESSUP = (int)ScanCode.SCANCODE_BRIGHTNESSUP | SCANCODE_MASK,
        DISPLAYSWITCH = (int)ScanCode.SCANCODE_DISPLAYSWITCH | SCANCODE_MASK,
        KBDILLUMTOGGLE = (int)ScanCode.SCANCODE_KBDILLUMTOGGLE | SCANCODE_MASK,
        KBDILLUMDOWN = (int)ScanCode.SCANCODE_KBDILLUMDOWN | SCANCODE_MASK,
        KBDILLUMUP = (int)ScanCode.SCANCODE_KBDILLUMUP | SCANCODE_MASK,
        EJECT = (int)ScanCode.SCANCODE_EJECT | SCANCODE_MASK,
        SLEEP = (int)ScanCode.SCANCODE_SLEEP | SCANCODE_MASK,
        APP1 = (int)ScanCode.SCANCODE_APP1 | SCANCODE_MASK,
        APP2 = (int)ScanCode.SCANCODE_APP2 | SCANCODE_MASK,
        AUDIOREWIND = (int)ScanCode.SCANCODE_AUDIOREWIND | SCANCODE_MASK,
        AUDIOFASTFORWARD = (int)ScanCode.SCANCODE_AUDIOFASTFORWARD | SCANCODE_MASK,
    }

    [Flags]
    public enum KeyMod : ushort
    {
        NONE = 0x0000,
        LSHIFT = 0x0001,
        RSHIFT = 0x0002,
        LCTRL = 0x0040,
        RCTRL = 0x0080,
        LALT = 0x0100,
        RALT = 0x0200,
        LGUI = 0x0400,
        RGUI = 0x0800,
        NUM = 0x1000,
        CAPS = 0x2000,
        MODE = 0x4000,
        SCROLL = 0x8000,
        CTRL = (LCTRL | RCTRL),
        SHIFT = (LSHIFT | RSHIFT),
        ALT = (LALT | RALT),
        GUI = (LGUI | RGUI)
    }

    public enum Icons
    {
        NONE = 0x0,
        ENTYPO_ICON_500PX = 0x0000F100,
        ENTYPO_ICON_500PX_WITH_CIRCLE = 0x0000F101,
        ENTYPO_ICON_ADD_TO_LIST = 0x0000F102,
        ENTYPO_ICON_ADD_USER = 0x0000F103,
        ENTYPO_ICON_ADDRESS = 0x0000F104,
        ENTYPO_ICON_ADJUST = 0x0000F105,
        ENTYPO_ICON_AIR = 0x0000F106,
        ENTYPO_ICON_AIRCRAFT = 0x0000F107,
        ENTYPO_ICON_AIRCRAFT_LANDING = 0x0000F108,
        ENTYPO_ICON_AIRCRAFT_TAKE_OFF = 0x0000F109,
        ENTYPO_ICON_ALIGN_BOTTOM = 0x0000F10A,
        ENTYPO_ICON_ALIGN_HORIZONTAL_MIDDLE = 0x0000F10B,
        ENTYPO_ICON_ALIGN_LEFT = 0x0000F10C,
        ENTYPO_ICON_ALIGN_RIGHT = 0x0000F10D,
        ENTYPO_ICON_ALIGN_TOP = 0x0000F10E,
        ENTYPO_ICON_ALIGN_VERTICAL_MIDDLE = 0x0000F10F,
        ENTYPO_ICON_APP_STORE = 0x0000F110,
        ENTYPO_ICON_ARCHIVE = 0x0000F111,
        ENTYPO_ICON_AREA_GRAPH = 0x0000F112,
        ENTYPO_ICON_ARROW_BOLD_DOWN = 0x0000F113,
        ENTYPO_ICON_ARROW_BOLD_LEFT = 0x0000F114,
        ENTYPO_ICON_ARROW_BOLD_RIGHT = 0x0000F115,
        ENTYPO_ICON_ARROW_BOLD_UP = 0x0000F116,
        ENTYPO_ICON_ARROW_DOWN = 0x0000F117,
        ENTYPO_ICON_ARROW_LEFT = 0x0000F118,
        ENTYPO_ICON_ARROW_LONG_DOWN = 0x0000F119,
        ENTYPO_ICON_ARROW_LONG_LEFT = 0x0000F11A,
        ENTYPO_ICON_ARROW_LONG_RIGHT = 0x0000F11B,
        ENTYPO_ICON_ARROW_LONG_UP = 0x0000F11C,
        ENTYPO_ICON_ARROW_RIGHT = 0x0000F11D,
        ENTYPO_ICON_ARROW_UP = 0x0000F11E,
        ENTYPO_ICON_ARROW_WITH_CIRCLE_DOWN = 0x0000F11F,
        ENTYPO_ICON_ARROW_WITH_CIRCLE_LEFT = 0x0000F120,
        ENTYPO_ICON_ARROW_WITH_CIRCLE_RIGHT = 0x0000F121,
        ENTYPO_ICON_ARROW_WITH_CIRCLE_UP = 0x0000F122,
        ENTYPO_ICON_ATTACHMENT = 0x0000F123,
        ENTYPO_ICON_AWARENESS_RIBBON = 0x0000F124,
        ENTYPO_ICON_BACK = 0x0000F125
            , ENTYPO_ICON_BACK_IN_TIME = 0x0000F126
            , ENTYPO_ICON_BAIDU = 0x0000F127
            , ENTYPO_ICON_BAR_GRAPH = 0x0000F128
            , ENTYPO_ICON_BASECAMP = 0x0000F129
            , ENTYPO_ICON_BATTERY = 0x0000F12A
            , ENTYPO_ICON_BEAMED_NOTE = 0x0000F12B
            , ENTYPO_ICON_BEHANCE = 0x0000F12C
            , ENTYPO_ICON_BELL = 0x0000F12D
            , ENTYPO_ICON_BLACKBOARD = 0x0000F12E
            , ENTYPO_ICON_BLOCK = 0x0000F12F
            , ENTYPO_ICON_BOOK = 0x0000F130
            , ENTYPO_ICON_BOOKMARK = 0x0000F131
            , ENTYPO_ICON_BOOKMARKS = 0x0000F132
            , ENTYPO_ICON_BOWL = 0x0000F133
            , ENTYPO_ICON_BOX = 0x0000F134
            , ENTYPO_ICON_BRIEFCASE = 0x0000F135
            , ENTYPO_ICON_BROWSER = 0x0000F136
            , ENTYPO_ICON_BRUSH = 0x0000F137
            , ENTYPO_ICON_BUCKET = 0x0000F138
            , ENTYPO_ICON_BUG = 0x0000F139
            , ENTYPO_ICON_CAKE = 0x0000F13A
            , ENTYPO_ICON_CALCULATOR = 0x0000F13B
            , ENTYPO_ICON_CALENDAR = 0x0000F13C
            , ENTYPO_ICON_CAMERA = 0x0000F13D
            , ENTYPO_ICON_CCW = 0x0000F13E
            , ENTYPO_ICON_CHAT = 0x0000F13F
            , ENTYPO_ICON_CHECK = 0x0000F140
            , ENTYPO_ICON_CHEVRON_DOWN = 0x0000F141
            , ENTYPO_ICON_CHEVRON_LEFT = 0x0000F142
            , ENTYPO_ICON_CHEVRON_RIGHT = 0x0000F143
            , ENTYPO_ICON_CHEVRON_SMALL_DOWN = 0x0000F144
            , ENTYPO_ICON_CHEVRON_SMALL_LEFT = 0x0000F145
            , ENTYPO_ICON_CHEVRON_SMALL_RIGHT = 0x0000F146
            , ENTYPO_ICON_CHEVRON_SMALL_UP = 0x0000F147
            , ENTYPO_ICON_CHEVRON_THIN_DOWN = 0x0000F148
            , ENTYPO_ICON_CHEVRON_THIN_LEFT = 0x0000F149
            , ENTYPO_ICON_CHEVRON_THIN_RIGHT = 0x0000F14A
            , ENTYPO_ICON_CHEVRON_THIN_UP = 0x0000F14B
            , ENTYPO_ICON_CHEVRON_UP = 0x0000F14C
            , ENTYPO_ICON_CHEVRON_WITH_CIRCLE_DOWN = 0x0000F14D
            , ENTYPO_ICON_CHEVRON_WITH_CIRCLE_LEFT = 0x0000F14E
            , ENTYPO_ICON_CHEVRON_WITH_CIRCLE_RIGHT = 0x0000F14F
            , ENTYPO_ICON_CHEVRON_WITH_CIRCLE_UP = 0x0000F150
            , ENTYPO_ICON_CIRCLE = 0x0000F151
            , ENTYPO_ICON_CIRCLE_WITH_CROSS = 0x0000F152
            , ENTYPO_ICON_CIRCLE_WITH_MINUS = 0x0000F153
            , ENTYPO_ICON_CIRCLE_WITH_PLUS = 0x0000F154
            , ENTYPO_ICON_CIRCULAR_GRAPH = 0x0000F155
            , ENTYPO_ICON_CLAPPERBOARD = 0x0000F156
            , ENTYPO_ICON_CLASSIC_COMPUTER = 0x0000F157
            , ENTYPO_ICON_CLIPBOARD = 0x0000F158
            , ENTYPO_ICON_CLOCK = 0x0000F159
            , ENTYPO_ICON_CLOUD = 0x0000F15A
            , ENTYPO_ICON_CODE = 0x0000F15B
            , ENTYPO_ICON_COG = 0x0000F15C
            , ENTYPO_ICON_COLOURS = 0x0000F15D
            , ENTYPO_ICON_COMPASS = 0x0000F15E
            , ENTYPO_ICON_CONTROLLER_FAST_BACKWARD = 0x0000F15F
            , ENTYPO_ICON_CONTROLLER_FAST_FORWARD = 0x0000F160
            , ENTYPO_ICON_CONTROLLER_JUMP_TO_START = 0x0000F161
            , ENTYPO_ICON_CONTROLLER_NEXT = 0x0000F162
            , ENTYPO_ICON_CONTROLLER_PAUS = 0x0000F163
            , ENTYPO_ICON_CONTROLLER_PLAY = 0x0000F164
            , ENTYPO_ICON_CONTROLLER_RECORD = 0x0000F165
            , ENTYPO_ICON_CONTROLLER_STOP = 0x0000F166
            , ENTYPO_ICON_CONTROLLER_VOLUME = 0x0000F167
            , ENTYPO_ICON_COPY = 0x0000F168
            , ENTYPO_ICON_CREATIVE_CLOUD = 0x0000F169
            , ENTYPO_ICON_CREATIVE_COMMONS = 0x0000F16A
            , ENTYPO_ICON_CREATIVE_COMMONS_ATTRIBUTION = 0x0000F16B
            , ENTYPO_ICON_CREATIVE_COMMONS_NODERIVS = 0x0000F16C
            , ENTYPO_ICON_CREATIVE_COMMONS_NONCOMMERCIAL_EU = 0x0000F16D
            , ENTYPO_ICON_CREATIVE_COMMONS_NONCOMMERCIAL_US = 0x0000F16E
            , ENTYPO_ICON_CREATIVE_COMMONS_PUBLIC_DOMAIN = 0x0000F16F
            , ENTYPO_ICON_CREATIVE_COMMONS_REMIX = 0x0000F170
            , ENTYPO_ICON_CREATIVE_COMMONS_SHARE = 0x0000F171
            , ENTYPO_ICON_CREATIVE_COMMONS_SHAREALIKE = 0x0000F172
            , ENTYPO_ICON_CREDIT = 0x0000F173
            , ENTYPO_ICON_CREDIT_CARD = 0x0000F174
            , ENTYPO_ICON_CROP = 0x0000F175
            , ENTYPO_ICON_CROSS = 0x0000F176
            , ENTYPO_ICON_CUP = 0x0000F177
            , ENTYPO_ICON_CW = 0x0000F178
            , ENTYPO_ICON_CYCLE = 0x0000F179
            , ENTYPO_ICON_DATABASE = 0x0000F17A
            , ENTYPO_ICON_DIAL_PAD = 0x0000F17B
            , ENTYPO_ICON_DIRECTION = 0x0000F17C
            , ENTYPO_ICON_DOCUMENT = 0x0000F17D
            , ENTYPO_ICON_DOCUMENT_LANDSCAPE = 0x0000F17E
            , ENTYPO_ICON_DOCUMENTS = 0x0000F17F
            , ENTYPO_ICON_DOT_SINGLE = 0x0000F180
            , ENTYPO_ICON_DOTS_THREE_HORIZONTAL = 0x0000F181
            , ENTYPO_ICON_DOTS_THREE_VERTICAL = 0x0000F182
            , ENTYPO_ICON_DOTS_TWO_HORIZONTAL = 0x0000F183
            , ENTYPO_ICON_DOTS_TWO_VERTICAL = 0x0000F184
            , ENTYPO_ICON_DOWNLOAD = 0x0000F185
            , ENTYPO_ICON_DRIBBBLE = 0x0000F186
            , ENTYPO_ICON_DRIBBBLE_WITH_CIRCLE = 0x0000F187
            , ENTYPO_ICON_DRINK = 0x0000F188
            , ENTYPO_ICON_DRIVE = 0x0000F189
            , ENTYPO_ICON_DROP = 0x0000F18A
            , ENTYPO_ICON_DROPBOX = 0x0000F18B
            , ENTYPO_ICON_EDIT = 0x0000F18C
            , ENTYPO_ICON_EMAIL = 0x0000F18D
            , ENTYPO_ICON_EMOJI_FLIRT = 0x0000F18E
            , ENTYPO_ICON_EMOJI_HAPPY = 0x0000F18F
            , ENTYPO_ICON_EMOJI_NEUTRAL = 0x0000F190
            , ENTYPO_ICON_EMOJI_SAD = 0x0000F191
            , ENTYPO_ICON_ERASE = 0x0000F192
            , ENTYPO_ICON_ERASER = 0x0000F193
            , ENTYPO_ICON_EVERNOTE = 0x0000F194
            , ENTYPO_ICON_EXPORT = 0x0000F195
            , ENTYPO_ICON_EYE = 0x0000F196
            , ENTYPO_ICON_EYE_WITH_LINE = 0x0000F197
            , ENTYPO_ICON_FACEBOOK = 0x0000F198
            , ENTYPO_ICON_FACEBOOK_WITH_CIRCLE = 0x0000F199
            , ENTYPO_ICON_FEATHER = 0x0000F19A
            , ENTYPO_ICON_FINGERPRINT = 0x0000F19B
            , ENTYPO_ICON_FLAG = 0x0000F19C
            , ENTYPO_ICON_FLASH = 0x0000F19D
            , ENTYPO_ICON_FLASHLIGHT = 0x0000F19E
            , ENTYPO_ICON_FLAT_BRUSH = 0x0000F19F
            , ENTYPO_ICON_FLATTR = 0x0000F1A0
            , ENTYPO_ICON_FLICKR = 0x0000F1A1
            , ENTYPO_ICON_FLICKR_WITH_CIRCLE = 0x0000F1A2
            , ENTYPO_ICON_FLOW_BRANCH = 0x0000F1A3
            , ENTYPO_ICON_FLOW_CASCADE = 0x0000F1A4
            , ENTYPO_ICON_FLOW_LINE = 0x0000F1A5
            , ENTYPO_ICON_FLOW_PARALLEL = 0x0000F1A6
            , ENTYPO_ICON_FLOW_TREE = 0x0000F1A7
            , ENTYPO_ICON_FLOWER = 0x0000F1A8
            , ENTYPO_ICON_FOLDER = 0x0000F1A9
            , ENTYPO_ICON_FOLDER_IMAGES = 0x0000F1AA
            , ENTYPO_ICON_FOLDER_MUSIC = 0x0000F1AB
            , ENTYPO_ICON_FOLDER_VIDEO = 0x0000F1AC
            , ENTYPO_ICON_FORWARD = 0x0000F1AD
            , ENTYPO_ICON_FOURSQUARE = 0x0000F1AE
            , ENTYPO_ICON_FUNNEL = 0x0000F1AF
            , ENTYPO_ICON_GAME_CONTROLLER = 0x0000F1B0
            , ENTYPO_ICON_GAUGE = 0x0000F1B1
            , ENTYPO_ICON_GITHUB = 0x0000F1B2
            , ENTYPO_ICON_GITHUB_WITH_CIRCLE = 0x0000F1B3
            , ENTYPO_ICON_GLOBE = 0x0000F1B4
            , ENTYPO_ICON_GOOGLE_DRIVE = 0x0000F1B5
            , ENTYPO_ICON_GOOGLE_HANGOUTS = 0x0000F1B6
            , ENTYPO_ICON_GOOGLE_PLAY = 0x0000F1B7
            , ENTYPO_ICON_GOOGLE_PLUS = 0x0000F1B8
            , ENTYPO_ICON_GOOGLE_PLUS_WITH_CIRCLE = 0x0000F1B9
            , ENTYPO_ICON_GRADUATION_CAP = 0x0000F1BA
            , ENTYPO_ICON_GRID = 0x0000F1BB
            , ENTYPO_ICON_GROOVESHARK = 0x0000F1BC
            , ENTYPO_ICON_HAIR_CROSS = 0x0000F1BD
            , ENTYPO_ICON_HAND = 0x0000F1BE
            , ENTYPO_ICON_HEART = 0x0000F1BF
            , ENTYPO_ICON_HEART_OUTLINED = 0x0000F1C0
            , ENTYPO_ICON_HELP = 0x0000F1C1
            , ENTYPO_ICON_HELP_WITH_CIRCLE = 0x0000F1C2
            , ENTYPO_ICON_HOME = 0x0000F1C3
            , ENTYPO_ICON_HOUR_GLASS = 0x0000F1C4
            , ENTYPO_ICON_HOUZZ = 0x0000F1C5
            , ENTYPO_ICON_ICLOUD = 0x0000F1C6
            , ENTYPO_ICON_IMAGE = 0x0000F1C7
            , ENTYPO_ICON_IMAGE_INVERTED = 0x0000F1C8
            , ENTYPO_ICON_IMAGES = 0x0000F1C9
            , ENTYPO_ICON_INBOX = 0x0000F1CA
            , ENTYPO_ICON_INFINITY = 0x0000F1CB
            , ENTYPO_ICON_INFO = 0x0000F1CC
            , ENTYPO_ICON_INFO_WITH_CIRCLE = 0x0000F1CD
            , ENTYPO_ICON_INSTAGRAM = 0x0000F1CE
            , ENTYPO_ICON_INSTAGRAM_WITH_CIRCLE = 0x0000F1CF
            , ENTYPO_ICON_INSTALL = 0x0000F1D0
            , ENTYPO_ICON_KEY = 0x0000F1D1
            , ENTYPO_ICON_KEYBOARD = 0x0000F1D2
            , ENTYPO_ICON_LAB_FLASK = 0x0000F1D3
            , ENTYPO_ICON_LANDLINE = 0x0000F1D4
            , ENTYPO_ICON_LANGUAGE = 0x0000F1D5
            , ENTYPO_ICON_LAPTOP = 0x0000F1D6
            , ENTYPO_ICON_LASTFM = 0x0000F1D7
            , ENTYPO_ICON_LASTFM_WITH_CIRCLE = 0x0000F1D8
            , ENTYPO_ICON_LAYERS = 0x0000F1D9
            , ENTYPO_ICON_LEAF = 0x0000F1DA
            , ENTYPO_ICON_LEVEL_DOWN = 0x0000F1DB
            , ENTYPO_ICON_LEVEL_UP = 0x0000F1DC
            , ENTYPO_ICON_LIFEBUOY = 0x0000F1DD
            , ENTYPO_ICON_LIGHT_BULB = 0x0000F1DE
            , ENTYPO_ICON_LIGHT_DOWN = 0x0000F1DF
            , ENTYPO_ICON_LIGHT_UP = 0x0000F1E0
            , ENTYPO_ICON_LINE_GRAPH = 0x0000F1E1
            , ENTYPO_ICON_LINK = 0x0000F1E2
            , ENTYPO_ICON_LINKEDIN = 0x0000F1E3
            , ENTYPO_ICON_LINKEDIN_WITH_CIRCLE = 0x0000F1E4,
        ENTYPO_ICON_LIST = 0x0000F1E5
            , ENTYPO_ICON_LOCATION = 0x0000F1E6
            , ENTYPO_ICON_LOCATION_PIN = 0x0000F1E7
            , ENTYPO_ICON_LOCK = 0x0000F1E8
            , ENTYPO_ICON_LOCK_OPEN = 0x0000F1E9
            , ENTYPO_ICON_LOG_OUT = 0x0000F1EA
            , ENTYPO_ICON_LOGIN = 0x0000F1EB
            , ENTYPO_ICON_LOOP = 0x0000F1EC
            , ENTYPO_ICON_MAGNET = 0x0000F1ED
            , ENTYPO_ICON_MAGNIFYING_GLASS = 0x0000F1EE
            , ENTYPO_ICON_MAIL = 0x0000F1EF
            , ENTYPO_ICON_MAIL_WITH_CIRCLE = 0x0000F1F0
            , ENTYPO_ICON_MAN = 0x0000F1F1
            , ENTYPO_ICON_MAP = 0x0000F1F2
            , ENTYPO_ICON_MASK = 0x0000F1F3
            , ENTYPO_ICON_MEDAL = 0x0000F1F4
            , ENTYPO_ICON_MEDIUM = 0x0000F1F5
            , ENTYPO_ICON_MEDIUM_WITH_CIRCLE = 0x0000F1F6
            , ENTYPO_ICON_MEGAPHONE = 0x0000F1F7
            , ENTYPO_ICON_MENU = 0x0000F1F8
            , ENTYPO_ICON_MERGE = 0x0000F1F9
            , ENTYPO_ICON_MESSAGE = 0x0000F1FA
            , ENTYPO_ICON_MIC = 0x0000F1FB
            , ENTYPO_ICON_MINUS = 0x0000F1FC
            , ENTYPO_ICON_MIXI = 0x0000F1FD
            , ENTYPO_ICON_MOBILE = 0x0000F1FE
            , ENTYPO_ICON_MODERN_MIC = 0x0000F1FF
            , ENTYPO_ICON_MOON = 0x0000F200
            , ENTYPO_ICON_MOUSE = 0x0000F201
            , ENTYPO_ICON_MOUSE_POINTER = 0x0000F202
            , ENTYPO_ICON_MUSIC = 0x0000F203
            , ENTYPO_ICON_NETWORK = 0x0000F204
            , ENTYPO_ICON_NEW = 0x0000F205
            , ENTYPO_ICON_NEW_MESSAGE = 0x0000F206
            , ENTYPO_ICON_NEWS = 0x0000F207
            , ENTYPO_ICON_NEWSLETTER = 0x0000F208
            , ENTYPO_ICON_NOTE = 0x0000F209
            , ENTYPO_ICON_NOTIFICATION = 0x0000F20A
            , ENTYPO_ICON_NOTIFICATIONS_OFF = 0x0000F20B
            , ENTYPO_ICON_OLD_MOBILE = 0x0000F20C
            , ENTYPO_ICON_OLD_PHONE = 0x0000F20D
            , ENTYPO_ICON_ONEDRIVE = 0x0000F20E
            , ENTYPO_ICON_OPEN_BOOK = 0x0000F20F
            , ENTYPO_ICON_PALETTE = 0x0000F210
            , ENTYPO_ICON_PAPER_PLANE = 0x0000F211
            , ENTYPO_ICON_PAYPAL = 0x0000F212
            , ENTYPO_ICON_PENCIL = 0x0000F213
            , ENTYPO_ICON_PHONE = 0x0000F214
            , ENTYPO_ICON_PICASA = 0x0000F215
            , ENTYPO_ICON_PIE_CHART = 0x0000F216
            , ENTYPO_ICON_PIN = 0x0000F217
            , ENTYPO_ICON_PINTEREST = 0x0000F218
            , ENTYPO_ICON_PINTEREST_WITH_CIRCLE = 0x0000F219
            , ENTYPO_ICON_PLUS = 0x0000F21A
            , ENTYPO_ICON_POPUP = 0x0000F21B
            , ENTYPO_ICON_POWER_PLUG = 0x0000F21C
            , ENTYPO_ICON_PRICE_RIBBON = 0x0000F21D
            , ENTYPO_ICON_PRICE_TAG = 0x0000F21E
            , ENTYPO_ICON_PRINT = 0x0000F21F
            , ENTYPO_ICON_PROGRESS_EMPTY = 0x0000F220
            , ENTYPO_ICON_PROGRESS_FULL = 0x0000F221
            , ENTYPO_ICON_PROGRESS_ONE = 0x0000F222
            , ENTYPO_ICON_PROGRESS_TWO = 0x0000F223
            , ENTYPO_ICON_PUBLISH = 0x0000F224
            , ENTYPO_ICON_QQ = 0x0000F225
            , ENTYPO_ICON_QQ_WITH_CIRCLE = 0x0000F226
            , ENTYPO_ICON_QUOTE = 0x0000F227
            , ENTYPO_ICON_RADIO = 0x0000F228
            , ENTYPO_ICON_RAFT = 0x0000F229
            , ENTYPO_ICON_RAFT_WITH_CIRCLE = 0x0000F22A
            , ENTYPO_ICON_RAINBOW = 0x0000F22B
            , ENTYPO_ICON_RDIO = 0x0000F22C
            , ENTYPO_ICON_RDIO_WITH_CIRCLE = 0x0000F22D
            , ENTYPO_ICON_REMOVE_USER = 0x0000F22E
            , ENTYPO_ICON_RENREN = 0x0000F22F
            , ENTYPO_ICON_REPLY = 0x0000F230
            , ENTYPO_ICON_REPLY_ALL = 0x0000F231
            , ENTYPO_ICON_RESIZE_100_PERCENT = 0x0000F232
            , ENTYPO_ICON_RESIZE_FULL_SCREEN = 0x0000F233,
        ENTYPO_ICON_RETWEET = 0x0000F234
            , ENTYPO_ICON_ROCKET = 0x0000F235
            , ENTYPO_ICON_ROUND_BRUSH = 0x0000F236
            , ENTYPO_ICON_RSS = 0x0000F237
            , ENTYPO_ICON_RULER = 0x0000F238
            , ENTYPO_ICON_SAVE = 0x0000F239
            , ENTYPO_ICON_SCISSORS = 0x0000F23A
            , ENTYPO_ICON_SCRIBD = 0x0000F23B
            , ENTYPO_ICON_SELECT_ARROWS = 0x0000F23C
            , ENTYPO_ICON_SHARE = 0x0000F23D
            , ENTYPO_ICON_SHARE_ALTERNATIVE = 0x0000F23E
            , ENTYPO_ICON_SHAREABLE = 0x0000F23F
            , ENTYPO_ICON_SHIELD = 0x0000F240
            , ENTYPO_ICON_SHOP = 0x0000F241
            , ENTYPO_ICON_SHOPPING_BAG = 0x0000F242
            , ENTYPO_ICON_SHOPPING_BASKET = 0x0000F243
            , ENTYPO_ICON_SHOPPING_CART = 0x0000F244
            , ENTYPO_ICON_SHUFFLE = 0x0000F245
            , ENTYPO_ICON_SIGNAL = 0x0000F246
            , ENTYPO_ICON_SINA_WEIBO = 0x0000F247
            , ENTYPO_ICON_SKYPE = 0x0000F248
            , ENTYPO_ICON_SKYPE_WITH_CIRCLE = 0x0000F249
            , ENTYPO_ICON_SLIDESHARE = 0x0000F24A
            , ENTYPO_ICON_SMASHING = 0x0000F24B
            , ENTYPO_ICON_SOUND = 0x0000F24C
            , ENTYPO_ICON_SOUND_MIX = 0x0000F24D
            , ENTYPO_ICON_SOUND_MUTE = 0x0000F24E
            , ENTYPO_ICON_SOUNDCLOUD = 0x0000F24F
            , ENTYPO_ICON_SPORTS_CLUB = 0x0000F250
            , ENTYPO_ICON_SPOTIFY = 0x0000F251
            , ENTYPO_ICON_SPOTIFY_WITH_CIRCLE = 0x0000F252
            , ENTYPO_ICON_SPREADSHEET = 0x0000F253
            , ENTYPO_ICON_SQUARED_CROSS = 0x0000F254
            , ENTYPO_ICON_SQUARED_MINUS = 0x0000F255
            , ENTYPO_ICON_SQUARED_PLUS = 0x0000F256
            , ENTYPO_ICON_STAR = 0x0000F257
            , ENTYPO_ICON_STAR_OUTLINED = 0x0000F258
            , ENTYPO_ICON_STOPWATCH = 0x0000F259
            , ENTYPO_ICON_STUMBLEUPON = 0x0000F25A
            , ENTYPO_ICON_STUMBLEUPON_WITH_CIRCLE = 0x0000F25B
            , ENTYPO_ICON_SUITCASE = 0x0000F25C
            , ENTYPO_ICON_SWAP = 0x0000F25D
            , ENTYPO_ICON_SWARM = 0x0000F25E
            , ENTYPO_ICON_SWEDEN = 0x0000F25F
            , ENTYPO_ICON_SWITCH = 0x0000F260
            , ENTYPO_ICON_TABLET = 0x0000F261
            , ENTYPO_ICON_TABLET_MOBILE_COMBO = 0x0000F262
            , ENTYPO_ICON_TAG = 0x0000F263
            , ENTYPO_ICON_TEXT = 0x0000F264
            , ENTYPO_ICON_TEXT_DOCUMENT = 0x0000F265
            , ENTYPO_ICON_TEXT_DOCUMENT_INVERTED = 0x0000F266
            , ENTYPO_ICON_THERMOMETER = 0x0000F267
            , ENTYPO_ICON_THUMBS_DOWN = 0x0000F268
            , ENTYPO_ICON_THUMBS_UP = 0x0000F269
            , ENTYPO_ICON_THUNDER_CLOUD = 0x0000F26A
            , ENTYPO_ICON_TICKET = 0x0000F26B
            , ENTYPO_ICON_TIME_SLOT = 0x0000F26C
            , ENTYPO_ICON_TOOLS = 0x0000F26D
            , ENTYPO_ICON_TRAFFIC_CONE = 0x0000F26E
            , ENTYPO_ICON_TRASH = 0x0000F26F
            , ENTYPO_ICON_TREE = 0x0000F270
            , ENTYPO_ICON_TRIANGLE_DOWN = 0x0000F271
            , ENTYPO_ICON_TRIANGLE_LEFT = 0x0000F272
            , ENTYPO_ICON_TRIANGLE_RIGHT = 0x0000F273
            , ENTYPO_ICON_TRIANGLE_UP = 0x0000F274
            , ENTYPO_ICON_TRIPADVISOR = 0x0000F275
            , ENTYPO_ICON_TROPHY = 0x0000F276
            , ENTYPO_ICON_TUMBLR = 0x0000F277
            , ENTYPO_ICON_TUMBLR_WITH_CIRCLE = 0x0000F278
            , ENTYPO_ICON_TV = 0x0000F279
            , ENTYPO_ICON_TWITTER = 0x0000F27A
            , ENTYPO_ICON_TWITTER_WITH_CIRCLE = 0x0000F27B
            , ENTYPO_ICON_TYPING = 0x0000F27C
            , ENTYPO_ICON_UNINSTALL = 0x0000F27D
            , ENTYPO_ICON_UNREAD = 0x0000F27E
            , ENTYPO_ICON_UNTAG = 0x0000F27F
            , ENTYPO_ICON_UPLOAD = 0x0000F280
            , ENTYPO_ICON_UPLOAD_TO_CLOUD = 0x0000F281
            , ENTYPO_ICON_USER = 0x0000F282
            , ENTYPO_ICON_USERS = 0x0000F283
            , ENTYPO_ICON_V_CARD = 0x0000F284
            , ENTYPO_ICON_VIDEO = 0x0000F285
            , ENTYPO_ICON_VIDEO_CAMERA = 0x0000F286
            , ENTYPO_ICON_VIMEO = 0x0000F287
            , ENTYPO_ICON_VIMEO_WITH_CIRCLE = 0x0000F288
            , ENTYPO_ICON_VINE = 0x0000F289
            , ENTYPO_ICON_VINE_WITH_CIRCLE = 0x0000F28A
            , ENTYPO_ICON_VINYL = 0x0000F28B
            , ENTYPO_ICON_VK = 0x0000F28C
            , ENTYPO_ICON_VK_ALTERNITIVE = 0x0000F28D
            , ENTYPO_ICON_VK_WITH_CIRCLE = 0x0000F28E
            , ENTYPO_ICON_VOICEMAIL = 0x0000F28F
            , ENTYPO_ICON_WALLET = 0x0000F290,
        ENTYPO_ICON_WARNING = 0x0000F291,
        ENTYPO_ICON_WATER = 0x0000F292,
        ENTYPO_ICON_WINDOWS_STORE = 0x0000F293,
        ENTYPO_ICON_XING = 0x0000F294,
        ENTYPO_ICON_XING_WITH_CIRCLE = 0x0000F295,
        ENTYPO_ICON_YELP = 0x0000F296,
        ENTYPO_ICON_YOUKO = 0x0000F297,
        ENTYPO_ICON_YOUKO_WITH_CIRCLE = 0x0000F298,
        ENTYPO_ICON_YOUTUBE = 0x0000F299,
        ENTYPO_ICON_YOUTUBE_WITH_CIRCLE = 0x0000F29A

    }

}
